[book]
authors = ["lujingwei"]
language = "en"
multilingual = false
src = "src"
title = "Learn From Rust Std"

[rust]
edition = "2021"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output]

[output.html.playground]
editable = true
copy-js = true

[output.html]
additional-css = ["theme/style.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js", "mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/lujingwei002/learn-rust-std"
edit-url-template = "https://github.com/lujingwei002/learn-rust-std/edit/main/{path}"

[output.html.fold]
enable = true